name: Build docker image and push to GitHub Packages

on:
  push:
    branches:
      - "develop"
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
  
    - name: Set env
      run: |
        if [ "${{ github.event_name }}" = "push" ] && [ ! "`echo $GITHUB_REF | grep develop`" ]; then
            echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        else
            echo "TAG=latest" >> $GITHUB_ENV
        fi
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: "`db-redis` build and push"
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/ktra.Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/ktra:db-redis-${{ env.TAG }}
        no-cache: true
        build-args: |
          DB=db-redis
        push: true
    
    - name: "`db-mongo` build and push"
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/ktra.Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/ktra:db-mongo-${{ env.TAG }}
        no-cache: true
        build-args: |
          DB=db-mongo
        push: true
    
    - name: "`db-sled` build and push"
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/ktra.Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/ktra:${{ env.TAG }}
        push: true

    - name: "`db-redis + openid` build and push"
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/ktra_openid.Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/ktra:db-redis-openid-${{ env.TAG }}
        no-cache: true
        build-args: |
          DB=db-redis
        push: true

    - name: "`db-mongo + openid` build and push"
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/ktra_openid.Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/ktra:db-mongo-openid-${{ env.TAG }}
        no-cache: true
        build-args: |
          DB=db-mongo
        push: true

    - name: "`db-sled + openid` build and push"
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/ktra_openid.Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/ktra:openid-${{ env.TAG }}
        push: true
